### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by vsierra08** [integromat/vscode-apps-sdk#27] opened 2020-04-06 22:38 UTC
- Issue Type: `Performance`
- Extension Name: `apps-sdk`
- Extension Version: `1.2.5`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Victor O sierra F\Integromat.apps-sdk-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by ma-zal** [comment] 2023-07-12 08:53
@vsierra08  Are you facing this issue also in last pre-release version 1.3.20?
If issue is still there, try to temporary disable autosave in VS Code to find that this is the root cause.

**Comment by ma-zal** [comment] 2023-09-24 19:15
Closing as outdated.

**Closed by ma-zal** 2023-09-24 19:15 UTC
