### ISSUE TITLE
Importing app

### ISSUE THREAD

**Issue by elmira-aldenova** [integromat/vscode-apps-sdk#28] opened 2020-04-30 10:46 UTC
Hi
I found an issue with importing app. I exported app using your SDK and then tried to import it. And I got an error: Cannot read property 'getDataAsync' of undefined.
SDK version: 1.2.6.

Can you please give me some feedback when this issue is resolved?
In general my team is trying to establish a development process for our app in Integromat. And we thought that we can use export/import features but then we faced with this issue.
Maybe you can provide an archive of app that can be successfully imported?

**Comment by dominikkadera** [comment] 2020-04-30 18:03
Hey @elmira-aldenova,
thanks for the report! Could you please post the name of the App you've tried to import? It would help with resolving this issue.
Thanks,
Dominik

**Comment by elmira-aldenova** [comment] 2020-05-06 08:00
@dominikkadera, it's ilevel-app-poc-440995. After the export SDK created an archive with the name ilevel-app-poc-440995.v1.zip.

**Comment by elmira-aldenova** [comment] 2020-05-12 08:14
Hi @dominikkadera,
Can you provide any updates related to the issue?

**Comment by dominikkadera** [comment] 2020-05-12 09:30
Hi @elmira-aldenova,
a new version of the Extension, `1.2.7`, which contains a fix for this issue, is just about to be released, you should receive an update soon.

**Comment by elmira-aldenova** [comment] 2020-05-12 09:32
Great! @dominikkadera, thank you!

**Comment by dominikkadera** [comment] 2020-05-13 06:59
Hi @elmira-aldenova, 
so the new version has been released. Could you please verify that the issue is fixed for you?
Thanks a lot!

**Comment by elmira-aldenova** [comment] 2020-05-13 10:19
Hi @dominikkadera, I tried to import the app again and it worked. Thank you for your help!
And I want to ask you a question. Does your team have plans to implement a CLI?

**Comment by elmira-aldenova** [comment] 2020-05-13 10:29
And one more question. So, the importing process doesn't support updating/overwriting of the existing app?

**Comment by dominikkadera** [comment] 2020-05-13 11:04
Cool, thanks for verifying.
Currently, no CLI is planned, but it's an interesting idea - could you please specify more what would you expect from the CLI?

Nope, currently, only a new app can be created by the import, but overwrite is not supported (yet).

Closing this as the original issue was resolved.

**Closed by dominikkadera** 2020-05-13 11:04 UTC

**Comment by elmira-aldenova** [comment] 2020-05-13 11:14
It would be helpful to have a CLI that can be used for deploying a new version of the app.
