### ISSUE TITLE
Import App Error: The value of "options.maxOutputLength" is out of range. It must be >= 1 and <= 34359738367. Received 0

### ISSUE THREAD

**Issue by jamessynergetic** [integromat/vscode-apps-sdk#195] opened 2024-08-27 15:21 UTC
When I export an app, and then reimport the ZIP. I get this error:

ERROR: The value of "options.maxOutputLength" is out of range. It must be >= 1 and <= 34359738367. Received 0
ERROR: 	STACK: RangeError: The value of "options.maxOutputLength" is out of range. It must be >= 1 and <= 34359738367. Received 0

at InflateRaw.ZlibBase (node:zlib:278:23)
	at InflateRaw.Zlib (node:zlib:695:3)
	at new InflateRaw (node:zlib:776:3)
	at Object.value [as createInflateRaw] (node:zlib:880:14)
	at Object.inflateAsync (/Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/node_modules/adm-zip/methods/inflater.js:13:28)
	at decompress (/Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/node_modules/adm-zip/zipEntry.js:87:30)
	at getDataAsync (/Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/node_modules/adm-zip/zipEntry.js:276:17)
	at /Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/utils.js:15:13
	at new Promise (<anonymous>)
	at /Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/utils.js:14:16
	at getData (/Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/commands/AppCommands.js:934:54)
	at parseApp (/Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/commands/AppCommands.js:998:37)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/commands/AppCommands.js:1156:25
	at async /Users/jamesalexander/.cursor/extensions/integromat.apps-sdk-2.0.0/out/error-handling.js:156:20
	at async m.h (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:163:206401)
	
	Tested import on several workspaces, to no avail.

**Comment by ma-zal** [comment] 2024-09-25 12:03
Most probably root cause: Bug in `adm-zip` lib. Update should help.

Original issue: https://github.com/cthackers/adm-zip/issues/496

**Comment by ma-zal** [comment] 2024-09-25 12:21
Should by fixed by https://github.com/integromat/vscode-apps-sdk/pull/201

**Closed by ma-zal** 2024-09-25 12:21 UTC
